"""
Local POPE (Polling-based Object Probing Evaluation) adapter.

Parses local POPE benchmark query files in JSON or JSONL format.

CRITICAL METHODOLOGICAL SAFEGUARDS:
1. POPE query questions (e.g. 'Is there a dog in the image?') and benchmark labels
   ('yes' / 'no') are benchmark probe targets, NOT claims generated by the VLM.
2. POPE reference labels are derived from dataset annotation presence heuristics,
   not independently verified human visual ground truth.
3. Unsupported formats and corrupted/unresolved image references are explicitly
   rejected with actionable errors, never silently guessed.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Any, Union
import json
import re

from src.data.schemas import DatasetSource


@dataclass
class POPEReferenceRecord:
    """
    Representation of a single POPE benchmark probe record.

    Attributes:
        question_id: Integer or string unique question ID in the POPE benchmark.
        raw_image_reference: Original image filename or reference string.
        canonical_image_id: Canonical normalized image ID (e.g. 'coco_123456').
        question_text: Original question text (e.g. 'Is there a dog in the image?').
        benchmark_label: 'yes' (present) or 'no' (absent in reference annotations).
        category_name: Canonical object category name being queried.
        variant: POPE benchmark split variant ('adversarial', 'popular', 'random', 'unknown').
        segment: Optional segment ('coco', 'aokvqa', 'gqa').
        metadata: Raw JSON payload and provenance information.
    """
    question_id: Union[int, str]
    raw_image_reference: str
    canonical_image_id: str
    question_text: str
    benchmark_label: str
    category_name: str
    variant: str = "unknown"
    segment: str = "coco"
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        self.benchmark_label = self.benchmark_label.strip().lower()
        if self.benchmark_label not in ("yes", "no"):
            raise ValueError(
                f"Invalid POPE benchmark label '{self.benchmark_label}'. Expected 'yes' or 'no'."
            )
        self.category_name = self.category_name.strip().lower()
        if not self.category_name:
            raise ValueError("category_name cannot be empty")


def parse_canonical_coco_id_from_image_ref(image_ref: str) -> str:
    """
    Extract canonical image ID 'coco_{int_id}' from a COCO image filename or ID string.

    Examples:
        'COCO_val2014_000000123456.jpg' -> 'coco_123456'
        '000000123456.jpg'              -> 'coco_123456'
        '123456'                        -> 'coco_123456'
        'coco_123456'                   -> 'coco_123456'
    """
    cleaned = Path(image_ref).stem.strip()

    # If already in 'coco_123' format
    if cleaned.startswith("coco_"):
        num_part = cleaned[5:]
        if num_part.isdigit():
            return f"coco_{int(num_part)}"

    # Match COCO pattern with digits at end
    match = re.search(r"(\d+)$", cleaned)
    if match:
        int_id = int(match.group(1))
        return f"coco_{int_id}"

    raise ValueError(
        f"Unable to resolve canonical image ID from POPE image reference: '{image_ref}'. "
        "Expected filename ending in integer digits (e.g. 'COCO_val2014_000000123456.jpg')."
    )


class POPEAdapter:
    """
    Adapter for loading and querying POPE benchmark query files.

    Attributes:
        file_path: Path to POPE JSON or JSONL file.
        records: List of POPEReferenceRecord instances.
        records_by_image: Dict mapping canonical_image_id -> List[POPEReferenceRecord].
        variant: Identified benchmark variant.
        provenance: File loading metadata.
    """

    def __init__(self, file_path: Union[str, Path], variant: Optional[str] = None):
        self.file_path = Path(file_path)
        self.records: List[POPEReferenceRecord] = []
        self.records_by_image: Dict[str, List[POPEReferenceRecord]] = {}
        self.variant: str = variant or "unknown"
        self.provenance: Dict[str, Any] = {}

        self._load_and_parse()

    def _infer_variant_from_path(self) -> str:
        name = self.file_path.name.lower()
        if "adversarial" in name:
            return "adversarial"
        elif "popular" in name:
            return "popular"
        elif "random" in name:
            return "random"
        return self.variant

    def _load_and_parse(self):
        if not self.file_path.exists():
            raise FileNotFoundError(f"POPE file not found: {self.file_path}")

        inferred_variant = self._infer_variant_from_path()
        raw_lines: List[Dict[str, Any]] = []

        with open(self.file_path, "r", encoding="utf-8") as f:
            content = f.read().strip()
            if not content:
                raise ValueError(f"POPE file at {self.file_path} is empty")

            # Try parsing as whole JSON list first
            if content.startswith("[") and content.endswith("]"):
                try:
                    raw_lines = json.loads(content)
                except json.JSONDecodeError as e:
                    raise ValueError(f"Invalid JSON list in {self.file_path}: {e}")
            else:
                # Parse as JSONL line by line
                for line_idx, line in enumerate(content.splitlines(), start=1):
                    line_str = line.strip()
                    if not line_str:
                        continue
                    try:
                        obj = json.loads(line_str)
                        if not isinstance(obj, dict):
                            raise ValueError(f"Line {line_idx} is not a JSON object")
                        raw_lines.append(obj)
                    except json.JSONDecodeError as e:
                        raise ValueError(f"Malformed JSON on line {line_idx} of {self.file_path}: {e}")

        if not raw_lines:
            raise ValueError(f"No valid POPE records found in {self.file_path}")

        for idx, row in enumerate(raw_lines):
            # Validate required fields
            q_id = row.get("question_id", idx)
            img_ref = row.get("image")
            if not img_ref:
                raise ValueError(f"Record {idx} in {self.file_path} is missing 'image' field")

            q_text = row.get("text") or row.get("question")
            if not q_text:
                raise ValueError(f"Record {idx} in {self.file_path} is missing question text ('text' or 'question')")

            label = row.get("label")
            if not label:
                raise ValueError(f"Record {idx} in {self.file_path} is missing 'label' field ('yes'/'no')")

            # Extract category name from explicit field or query text
            category = row.get("category")
            if not category:
                # Try inferring category from question 'Is there a <category> in the image?'
                match = re.search(r"(?:is there|find|see)\s+(?:a|an)?\s+([a-zA-Z\s]+?)\s+(?:in|on|\?)", q_text, re.IGNORECASE)
                if match:
                    category = match.group(1).strip()
                else:
                    category = "object"

            canonical_img_id = parse_canonical_coco_id_from_image_ref(str(img_ref))
            record_variant = row.get("variant", inferred_variant)

            rec = POPEReferenceRecord(
                question_id=q_id,
                raw_image_reference=str(img_ref),
                canonical_image_id=canonical_img_id,
                question_text=str(q_text),
                benchmark_label=str(label),
                category_name=str(category),
                variant=record_variant,
                segment=row.get("segment", "coco"),
                metadata=row,
            )
            self.records.append(rec)
            if canonical_img_id not in self.records_by_image:
                self.records_by_image[canonical_img_id] = []
            self.records_by_image[canonical_img_id].append(rec)

        self.provenance = {
            "source_file": str(self.file_path.name),
            "variant": inferred_variant,
            "num_records": len(self.records),
            "num_unique_images": len(self.records_by_image),
        }

    def get_records_for_image(self, canonical_image_id: str) -> List[POPEReferenceRecord]:
        """Get all POPE benchmark questions and reference labels for a canonical image ID."""
        return self.records_by_image.get(canonical_image_id, [])
